<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.5.0.2 setup script
 * Date: Wed, 30 Sep 2015 19:31:59 +0300
 */

$cfg['DefaultLang'] = 'ru';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>